use crate::game::macros::r#enum::define_u8_enum;

define_u8_enum! {
    pub enum Item {
        MasterBall = 0x01,
        UltraBall = 0x02,
        Brightpowder = 0x03,
        GreatBall = 0x04,
        PokeBall = 0x05,
        MoonStone = 0x08,
        FireStone = 0x16,
        Thunderstone = 0x17,
        WaterStone = 0x18,
        LeafStone = 0x22,
        QuickClaw = 0x49,
        SoftSand = 0x4c,
        SharpBeak = 0x4d,
        PoisonBarb = 0x51,
        KingsRock = 0x52,
        BitterBerry = 0x53,
        MintBerry = 0x54,
        MysticWater = 0x5f,
        Twistedspoon = 0x60,
        Blackbelt = 0x62,
        Blackglasses = 0x66,
        Magnet = 0x6c,
        PinkBow = 0x68,
        Nevermeltice = 0x6b,
        Miracleberry = 0x6d,
        Everstone = 0x70,
        SpellTag = 0x71,
        MiracleSeed = 0x75,
        FocusBand = 0x77,
        HardStone = 0x7d,
        Charcoal = 0x8a,
        BerryJuice = 0x8b,
        ScopeLens = 0x8c,
        MetalCoat = 0x8f,
        Leftovers = 0x92,
        DragonScale = 0x97,
        BerserkGene = 0x98,
        HeavyBall = 0x9d,
        LevelBall = 0x9f,
        LureBall = 0xa0,
        FastBall = 0xa1,
        LightBall = 0xa3,
        FriendBall = 0xa4,
        MoonBall = 0xa5,
        LoveBall = 0xa6,
        SunStone = 0xa9,
        UpGrade = 0xac,
        GoldBerry = 0xae,
        Berry = 0xad,
        ParkBall = 0xb1,
        BrickPiece = 0xb4,
    }
}

pub const SAFARI_BALL: Item = Item::MoonStone; // leftovers from red

pub const NUM_TMS: usize = 50;
pub const NUM_HMS: usize = 7;
