use crate::game::macros::r#enum::define_u8_enum;

define_u8_enum! {
    pub enum Mart {
        Cherrygrove = 0,
        CherrygroveDex = 1,
        Violet = 2,
        Azalea = 3,
        Cianwood = 4,
        Goldenrod2F1 = 5,
        Goldenrod2F2 = 6,
        Goldenrod3F = 7,
        Goldenrod4F = 8,
        Goldenrod5F1 = 9,
        Goldenrod5F2 = 10,
        Goldenrod5F3 = 11,
        Goldenrod5F4 = 12,
        Olivine = 13,
        Ecruteak = 14,
        Mahogany1 = 15,
        Mahogany2 = 16,
        Blackthorn = 17,
        Viridian = 18,
        Pewter = 19,
        Cerulean = 20,
        Lavender = 21,
        Vermilion = 22,
        Celadon2F1 = 23,
        Celadon2F2 = 24,
        Celadon3F = 25,
        Celadon4F = 26,
        Celadon5F1 = 27,
        Celadon5F2 = 28,
        Fuchsia = 29,
        Saffron = 30,
        MtMoon = 31,
        IndigoPlateau = 32,
        Underground = 33,
    }
}
